python train.py --run_id vit_tiny_dummy_test --model_type original --dataset mnist --batch_size 256 --epochs 5 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 6 --num_heads_original 8 --embed_dim_original 64 --mlp_dim_original 128
python test.py --run_id vit_tiny_dummy_test --model_type original --dataset mnist --batch_size 256 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 6 --num_heads_original 8 --embed_dim_original 64 --mlp_dim_original 128

python train.py --run_id vit_small_dummy_test --model_type original --dataset mnist --batch_size 256 --epochs 5 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 9 --num_heads_original 12 --embed_dim_original 192 --mlp_dim_original 384
python test.py --run_id vit_small_dummy_test --model_type original --dataset mnist --batch_size 256 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 9 --num_heads_original 12 --embed_dim_original 192 --mlp_dim_original 384

python train.py --run_id vit_tiny_tensorized_dummy_test_tle --model_type tensorized --dataset mnist --batch_size 256 --epochs 5 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 6 --num_heads 2 2 2 --embed_dim 4 4 4 --mlp_dim 4 4 8 --tensor_method_mlp tle tle --tensor_method tle --reduce_level 0 0 0
python test.py --run_id vit_tiny_tensorized_dummy_test_tle --model_type tensorized --dataset mnist --batch_size 256 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 6 --num_heads 2 2 2 --embed_dim 4 4 4 --mlp_dim 4 4 8 --tensor_method_mlp tle tle --tensor_method tle --reduce_level 0 0 0

python train.py --run_id vit_tiny_tensorized_dummy_test_tdle --model_type tensorized --dataset mnist --batch_size 256 --epochs 5 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 6 --num_heads 2 2 2 --embed_dim 4 4 4 --mlp_dim 4 4 8 --tensor_method_mlp tdle tdle --tensor_method tdle --tdle_level 3 --reduce_level 0 0 0
python test.py --run_id vit_tiny_tensorized_dummy_test_tdle --model_type tensorized --dataset mnist --batch_size 256 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 6 --num_heads 2 2 2 --embed_dim 4 4 4 --mlp_dim 4 4 8 --tensor_method_mlp tdle tdle --tensor_method tdle --tdle_level 3 --reduce_level 0 0 0

python train.py --run_id vit_tiny_tensorized_dummy_test_tle_tp --model_type tensorized --dataset mnist --batch_size 256 --epochs 5 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 6 --num_heads 2 2 2 --embed_dim 4 4 4 --mlp_dim 4 4 8 --tensor_method_mlp tle tp --tensor_method tle --reduce_level 0 0 0
python test.py --run_id vit_tiny_tensorized_dummy_test_tle_tp --model_type tensorized --dataset mnist --batch_size 256 --image_size 32 --patch_size 4 --num_classes 10 --num_layers 6 --num_heads 2 2 2 --embed_dim 4 4 4 --mlp_dim 4 4 8 --tensor_method_mlp tle tp --tensor_method tle --reduce_level 0 0 0
